### ISSUE TITLE
API endpoints

### ISSUE THREAD

**Issue by gregurco** [pshon/vcapi#6]
Привет.
Хотел бы узнать как ты выловил api endpoints, к которым нужно обращаться за данными. Эти линки нигде не опубликованны и администрация проекта их, вроде как, не разглашает. Я пытался выловить их используя прокси и sniffer, но без сертификата ничего увидеть не могу. В особенности хотел бы найти endoints для рынка.

**Comment by pshon** [comment]
Привет.
Все достаточно банально - просто распаковал apk и игрой и немного покопался в исходниках.
Выслал на почту файл со всем api который есть в игре.

**Comment by gregurco** [comment]
Спасибо, отлично. Скоро постараюсь добавить класс работы с рынком, а так же думаю для работы с аккаунтом пару методов (типа смены пароля).

**Comment by yanzay** [comment]
Привет, а можно и мне описание api?

**Comment by pshon** [comment]
Отправил.

05.01.2016 22:15, Alexey Grachov пишет:
